env:
  es2021: true
  node: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: off,
  import/extensions: off
}
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'